uploads = []

[[generated]]
id = "-rN8Vs-txjsG2MfwqGWZ0"
uri = "file://attached_assets/generated_images/gtw_logo.png"
type = "image"
title = "gtw logo icon"

[[outputs]]
id = "hXIB3GRaZINvCp4ZReS_T"
uri = "file://backend.md"
type = "text"
title = "ParcelPeer Full Backend Specification"

[[outputs]]
id = "ZMpSZU44WEte65KT2D8f_"
uri = "file://driver.md"
type = "text"
title = "ParcelPeer Driver App — Full Specification"

[[outputs]]
id = "53R3gIq06_isGCOihvVv5"
uri = "file://attached_assets/generated_images/gtw_logo.png"
type = "image"
title = "The GTW — App Logo"
