import { drizzle } from "drizzle-orm/node-postgres";
import { Pool } from "pg";
import { users, parcels, routes } from "../../shared/schema";

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const db = drizzle(pool);

const now = new Date();
const daysFromNow = (d: number) => new Date(now.getTime() + d * 86400000);
const hoursFromNow = (h: number) => new Date(now.getTime() + h * 3600000);

async function seed() {
  console.log("🌱 Seeding database...");

  // ── Users ──────────────────────────────────────────────────────────────────
  const seedUsers = await db.insert(users).values([
    {
      id: "user-amara-001",
      name: "Amara Khumalo",
      email: "amara@example.com",
      phone: "+27 82 111 2233",
      rating: 4.9,
      verified: true,
      emailVerified: true,
      walletBalance: 1250,
      subscriptionStatus: "free",
      bio: "Frequent sender based in Johannesburg. Fast responder.",
      city: "Johannesburg",
    },
    {
      id: "user-sipho-002",
      name: "Sipho Ndlovu",
      email: "sipho@example.com",
      phone: "+27 71 333 4455",
      rating: 4.7,
      verified: true,
      emailVerified: true,
      walletBalance: 3400,
      subscriptionStatus: "free",
      bio: "Carrier driving JHB ↔ Durban weekly. Reliable & careful.",
      city: "Johannesburg",
    },
    {
      id: "user-fatima-003",
      name: "Fatima Patel",
      email: "fatima@example.com",
      phone: "+27 83 555 6677",
      rating: 5.0,
      verified: true,
      emailVerified: true,
      walletBalance: 800,
      subscriptionStatus: "free",
      bio: "Cape Town sender — usually small packages.",
      city: "Cape Town",
    },
    {
      id: "user-lebo-004",
      name: "Lebo Mokoena",
      email: "lebo@example.com",
      phone: "+27 76 777 8899",
      rating: 4.6,
      verified: true,
      emailVerified: true,
      walletBalance: 5000,
      subscriptionStatus: "free",
      bio: "Road warrior. CPT ↔ PE ↔ JHB — ask me about any route.",
      city: "Cape Town",
    },
    {
      id: "user-thabo-005",
      name: "Thabo Sithole",
      email: "thabo@example.com",
      phone: "+27 79 999 0011",
      rating: 4.8,
      verified: true,
      emailVerified: true,
      walletBalance: 650,
      subscriptionStatus: "free",
      bio: "Pretoria-based sender, mostly documents and small items.",
      city: "Pretoria",
    },
    {
      id: "user-zanele-006",
      name: "Zanele Dlamini",
      email: "zanele@example.com",
      phone: "+27 84 221 3344",
      rating: 4.5,
      verified: false,
      emailVerified: true,
      walletBalance: 200,
      subscriptionStatus: "free",
      bio: "New to The GTW. Sending gifts to family.",
      city: "Durban",
    },
    {
      id: "user-ruan-007",
      name: "Ruan van der Berg",
      email: "ruan@example.com",
      phone: "+27 82 445 5566",
      rating: 4.9,
      verified: true,
      emailVerified: true,
      walletBalance: 9200,
      subscriptionStatus: "free",
      bio: "Long-haul carrier. JHB ↔ CPT corridor specialist.",
      city: "Johannesburg",
    },
    {
      id: "user-nomsa-008",
      name: "Nomsa Zulu",
      email: "nomsa@example.com",
      phone: "+27 73 667 7788",
      rating: 4.3,
      verified: true,
      emailVerified: true,
      walletBalance: 450,
      subscriptionStatus: "free",
      bio: "Sender in PE. Usually electronics and clothing.",
      city: "Port Elizabeth",
    },
  ]).returning();

  console.log(`✅ Inserted ${seedUsers.length} users`);

  // ── Parcels ────────────────────────────────────────────────────────────────
  const seedParcels = await db.insert(parcels).values([
    // Pending (available for carriers)
    {
      origin: "Johannesburg, Sandton",
      destination: "Durban, Umhlanga",
      originLat: -26.1076, originLng: 28.0567,
      destinationLat: -29.7248, destinationLng: 31.0789,
      size: "medium",
      weight: 3.5,
      description: "Nike sneakers in original box",
      compensation: 150,
      pickupDate: hoursFromNow(6),
      status: "Pending",
      senderId: "user-amara-001",
      receiverName: "Sipho's cousin",
      receiverPhone: "+27 71 000 1111",
    },
    {
      origin: "Cape Town, CBD",
      destination: "Johannesburg, Rosebank",
      originLat: -33.9249, originLng: 18.4241,
      destinationLat: -26.1484, destinationLng: 28.0426,
      size: "small",
      weight: 0.8,
      description: "Legal documents — signed contracts",
      isFragile: false,
      compensation: 120,
      pickupDate: hoursFromNow(4),
      status: "Pending",
      senderId: "user-fatima-003",
      receiverName: "Thabo Sithole",
      receiverPhone: "+27 79 999 0011",
    },
    {
      origin: "Pretoria, Centurion",
      destination: "Cape Town, Bellville",
      originLat: -25.8603, originLng: 28.1894,
      destinationLat: -33.8963, originLng: 18.6280,
      destinationLat: -33.8963, destinationLng: 18.6280,
      size: "large",
      weight: 12.0,
      description: "Baby cot + mattress, disassembled",
      isFragile: false,
      compensation: 350,
      pickupDate: daysFromNow(1),
      status: "Pending",
      senderId: "user-thabo-005",
      receiverName: "Zanele Dlamini",
      receiverPhone: "+27 84 221 3344",
    },
    {
      origin: "Durban, Berea",
      destination: "Johannesburg, Soweto",
      originLat: -29.8587, originLng: 31.0218,
      destinationLat: -26.2637, destinationLng: 27.8557,
      size: "small",
      weight: 0.5,
      description: "Handmade beaded necklaces (fragile)",
      isFragile: true,
      compensation: 80,
      pickupDate: hoursFromNow(12),
      status: "Pending",
      senderId: "user-zanele-006",
      receiverName: "Family member",
      receiverPhone: "+27 82 000 2222",
    },
    {
      origin: "Port Elizabeth, Summerstrand",
      destination: "Cape Town, Sea Point",
      originLat: -33.9968, originLng: 25.6744,
      destinationLat: -33.9182, destinationLng: 18.3868,
      size: "medium",
      weight: 5.0,
      description: "Surfboard fins + wetsuit",
      compensation: 200,
      pickupDate: daysFromNow(2),
      status: "Pending",
      senderId: "user-nomsa-008",
      receiverName: "Lebo Mokoena",
      receiverPhone: "+27 76 777 8899",
    },
    // Paid (ready for carrier pickup)
    {
      origin: "Johannesburg, Fourways",
      destination: "Pretoria, Brooklyn",
      originLat: -25.9971, originLng: 28.0067,
      destinationLat: -25.7639, destinationLng: 28.2372,
      size: "small",
      weight: 1.2,
      description: "Birthday cake — handle with care",
      isFragile: true,
      compensation: 60,
      pickupDate: hoursFromNow(2),
      status: "Paid",
      senderId: "user-amara-001",
      receiverName: "Mom",
      receiverPhone: "+27 82 333 4444",
    },
    {
      origin: "Cape Town, Stellenbosch",
      destination: "Cape Town, Camps Bay",
      originLat: -33.9321, originLng: 18.8602,
      destinationLat: -33.9489, destinationLng: 18.3771,
      size: "medium",
      weight: 4.0,
      description: "Case of wine (12 bottles) — fragile",
      isFragile: true,
      compensation: 180,
      pickupDate: hoursFromNow(8),
      status: "Paid",
      senderId: "user-fatima-003",
      receiverName: "Wine club member",
      receiverPhone: "+27 21 555 6677",
    },
    // In Transit
    {
      origin: "Johannesburg, OR Tambo area",
      destination: "Durban, Pinetown",
      originLat: -26.1367, originLng: 28.2411,
      destinationLat: -29.8219, destinationLng: 30.8575,
      size: "large",
      weight: 18.0,
      description: "Photography equipment — camera bodies, lenses",
      isFragile: true,
      compensation: 500,
      pickupDate: daysFromNow(-1),
      status: "In Transit",
      senderId: "user-thabo-005",
      transporterId: "user-sipho-002",
      receiverName: "Studio Photography Durban",
      receiverPhone: "+27 31 000 5555",
    },
    {
      origin: "Cape Town, Observatory",
      destination: "Johannesburg, Melville",
      originLat: -33.9392, originLng: 18.4725,
      destinationLat: -26.1762, destinationLng: 27.9943,
      size: "medium",
      weight: 6.0,
      description: "Vinyl record collection (30 LPs)",
      isFragile: true,
      compensation: 300,
      pickupDate: daysFromNow(-2),
      status: "In Transit",
      senderId: "user-lebo-004",
      transporterId: "user-ruan-007",
      receiverName: "Music collector",
      receiverPhone: "+27 82 888 9999",
    },
    // Accepted
    {
      origin: "Durban, uMlazi",
      destination: "Pretoria, Soshanguve",
      originLat: -29.9738, originLng: 30.8934,
      destinationLat: -25.5288, destinationLng: 28.0896,
      size: "medium",
      weight: 8.0,
      description: "School textbooks — Grade 12 bundle",
      compensation: 220,
      pickupDate: daysFromNow(1),
      status: "Accepted",
      senderId: "user-zanele-006",
      transporterId: "user-sipho-002",
      receiverName: "Student",
      receiverPhone: "+27 76 111 2222",
    },
    // Delivered
    {
      origin: "Johannesburg, Braamfontein",
      destination: "Cape Town, Wynberg",
      originLat: -26.1929, originLng: 28.0333,
      destinationLat: -34.0036, destinationLng: 18.4603,
      size: "small",
      weight: 1.5,
      description: "Laptop charger + accessories",
      compensation: 130,
      pickupDate: daysFromNow(-5),
      status: "Delivered",
      senderId: "user-amara-001",
      transporterId: "user-ruan-007",
      receiverName: "Cape Town office",
      receiverPhone: "+27 21 444 5566",
    },
    {
      origin: "Port Elizabeth, Newton Park",
      destination: "Durban, Musgrave",
      originLat: -33.9604, originLng: 25.5726,
      destinationLat: -29.8539, destinationLng: 31.0017,
      size: "small",
      weight: 2.0,
      description: "Prescription medication + supplements",
      compensation: 100,
      pickupDate: daysFromNow(-3),
      status: "Delivered",
      senderId: "user-nomsa-008",
      transporterId: "user-lebo-004",
      receiverName: "Patient",
      receiverPhone: "+27 31 222 3344",
    },
  ]).returning();

  console.log(`✅ Inserted ${seedParcels.length} parcels`);

  // ── Routes ─────────────────────────────────────────────────────────────────
  const seedRoutes = await db.insert(routes).values([
    {
      carrierId: "user-sipho-002",
      origin: "Johannesburg, Sandton",
      destination: "Durban, Umhlanga",
      originLat: -26.1076, originLng: 28.0567,
      destinationLat: -29.7248, destinationLng: 31.0789,
      departureDate: daysFromNow(1),
      departureTime: "06:00",
      frequency: "weekly",
      maxParcelSize: "large",
      maxWeight: 30.0,
      availableCapacity: 3,
      capacityUsed: 1,
      pricePerKg: 18,
      notes: "Drive every Monday. Comfortable SUV. Can carry up to 3 parcels. Non-fragile only unless well-packed.",
      status: "Active",
    },
    {
      carrierId: "user-ruan-007",
      origin: "Johannesburg, Randburg",
      destination: "Cape Town, CBD",
      originLat: -26.0926, originLng: 27.9973,
      destinationLat: -33.9249, destinationLng: 18.4241,
      departureDate: daysFromNow(3),
      departureTime: "05:00",
      frequency: "weekly",
      maxParcelSize: "large",
      maxWeight: 50.0,
      availableCapacity: 5,
      capacityUsed: 0,
      pricePerKg: 15,
      notes: "Long-haul JHB to CPT. Bakkie with canopy. Happy to handle fragile items with advance notice.",
      status: "Active",
    },
    {
      carrierId: "user-lebo-004",
      origin: "Cape Town, Sea Point",
      destination: "Port Elizabeth, Central",
      originLat: -33.9182, originLng: 18.3868,
      destinationLat: -33.9608, destinationLng: 25.6022,
      departureDate: daysFromNow(2),
      departureTime: "07:30",
      frequency: "one_time",
      maxParcelSize: "medium",
      maxWeight: 15.0,
      availableCapacity: 2,
      capacityUsed: 0,
      pricePerKg: 20,
      notes: "One-time coastal road trip. Can take up to 2 medium parcels. Pet-friendly car, no strong-smelling items please.",
      status: "Active",
    },
    {
      carrierId: "user-sipho-002",
      origin: "Durban, Pinetown",
      destination: "Johannesburg, Midrand",
      originLat: -29.8219, originLng: 30.8575,
      destinationLat: -25.9992, destinationLng: 28.1234,
      departureDate: daysFromNow(4),
      departureTime: "04:30",
      frequency: "weekly",
      maxParcelSize: "large",
      maxWeight: 40.0,
      availableCapacity: 4,
      capacityUsed: 2,
      pricePerKg: 17,
      notes: "Return leg from Durban every Thursday. Always on time. Truck with enclosed cargo area.",
      status: "Active",
    },
    {
      carrierId: "user-ruan-007",
      origin: "Cape Town, Bellville",
      destination: "Johannesburg, OR Tambo",
      originLat: -33.8963, originLng: 18.6280,
      destinationLat: -26.1367, destinationLng: 28.2411,
      departureDate: daysFromNow(6),
      departureTime: "05:30",
      frequency: "weekly",
      maxParcelSize: "large",
      maxWeight: 60.0,
      availableCapacity: 6,
      capacityUsed: 1,
      pricePerKg: 14,
      notes: "Weekly CPT→JHB run. Large capacity pickup truck. Electronics welcome, I drive carefully.",
      status: "Active",
    },
    {
      carrierId: "user-lebo-004",
      origin: "Port Elizabeth, Summerstrand",
      destination: "Pretoria, Arcadia",
      originLat: -33.9968, originLng: 25.6744,
      destinationLat: -25.7461, destinationLng: 28.2132,
      departureDate: daysFromNow(5),
      departureTime: "06:00",
      frequency: "one_time",
      maxParcelSize: "medium",
      maxWeight: 20.0,
      availableCapacity: 3,
      capacityUsed: 0,
      pricePerKg: 22,
      notes: "Long road trip PE to PTA. Happy to stop in JHB for drop-offs. Station wagon with roof rack.",
      status: "Active",
    },
  ]).returning();

  console.log(`✅ Inserted ${seedRoutes.length} routes`);
  console.log("\n🎉 Seed complete!");
  console.log(`   ${seedUsers.length} users | ${seedParcels.length} parcels | ${seedRoutes.length} routes`);

  await pool.end();
}

seed().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});
